export const mockTickets = [
  {
    id: "1404050180001",
    title: "Test Tech New",
    responsibleUnit: "واحد لورم ایپسوم",
    responsiblePerson: "علی افتخاری نیا",
    createdDate: "1404/05/18",
    status: "open",
    priority: "high",
    category: "technical",
  },
  {
    id: "1404050180002",
    title: "مشکل اتصال به سرور",
    responsibleUnit: "واحد فناوری اطلاعات",
    responsiblePerson: "محمد رضایی",
    createdDate: "1404/05/17",
    status: "in-progress",
    priority: "medium",
    category: "technical",
  },
  {
    id: "1404050180003",
    title: "درخواست تغییر رمز عبور",
    responsibleUnit: "واحد امنیت",
    responsiblePerson: "فاطمه احمدی",
    createdDate: "1404/05/16",
    status: "closed",
    priority: "low",
    category: "support",
  },
  {
    id: "1404050180004",
    title: "خطا در سیستم پرداخت",
    responsibleUnit: "واحد مالی",
    responsiblePerson: "حسین کریمی",
    createdDate: "1404/05/15",
    status: "open",
    priority: "high",
    category: "billing",
  },
]

export const mockUsers = [
  {
    id: 1,
    fullName: "علی افتخاری نیا",
    username: "ali.eftekhari",
    email: "ali@example.com",
    department: "فناوری اطلاعات",
    role: "admin",
    status: "active",
    createdDate: "1404/03/15",
  },
  {
    id: 2,
    fullName: "محمد رضایی",
    username: "mohammad.rezaei",
    email: "mohammad@example.com",
    department: "پشتیبانی",
    role: "support",
    status: "active",
    createdDate: "1404/03/10",
  },
  {
    id: 3,
    fullName: "فاطمه احمدی",
    username: "fatemeh.ahmadi",
    email: "fatemeh@example.com",
    department: "امنیت",
    role: "security",
    status: "inactive",
    createdDate: "1404/02/20",
  },
]

export const mockDashboardStats = {
  totalUsers: 156,
  totalTickets: 1247,
  activeTickets: 89,
  closedTickets: 1158,
  pendingTickets: 23,
  highPriorityTickets: 12,
}
